# Generated by Django 4.2 on 2023-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default.jpeg', upload_to='recipes/media', verbose_name='Картинка'),
        ),
    ]
