# Generated by Django 4.2 on 2023-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='recipes/media', verbose_name='Картинка'),
        ),
    ]
